country = Country.create(name: 'India')
state = State.create(
  [
    { country: country, name: 'Andhra Pradesh' },
    { country: country, name: 'Arunachal Pradesh' },
    { country: country, name: 'Assam' },
    { country: country, name: 'Bihar' },
    { country: country, name: 'Chhattisgarh' },
    { country: country, name: 'Goa' },
    { country: country, name: 'Gujarat' },
    { country: country, name: 'Haryana' },
    { country: country, name: 'Himachal Pradesh' },
    { country: country, name: 'Jharkhand' },
    { country: country, name: 'Karnataka' },
    { country: country, name: 'Kerala' },
    { country: country, name: 'Madhya Pradesh' },
    { country: country, name: 'Maharashtra' },
    { country: country, name: 'Manipur' },
    { country: country, name: 'Meghalaya' },
    { country: country, name: 'Mizoram' },
    { country: country, name: 'Nagaland' },
    { country: country, name: 'Odisha' },
    { country: country, name: 'Punjab' },
    { country: country, name: 'Rajasthan' },
    { country: country, name: 'Sikkim' },
    { country: country, name: 'Tamil Nadu' },
    { country: country, name: 'Tripura' },
    { country: country, name: 'Uttar Pradesh' },
    { country: country, name: 'Uttarakhand' },
    { country: country, name: 'West Bengal' },
    { country: country, name: 'Telangana' },
    { country: country, name: 'Andaman and Nicobar' },
    { country: country, name: 'Chandigarh' },
    { country: country, name: 'Daman and Diu' },
    { country: country, name: 'Dadra Nagar Haveli' },
    { country: country, name: 'Jammu and Kashmir' },
    { country: country, name: 'Ladakh' },
    { country: country, name: 'Lakshadweep' },
    { country: country, name: 'Delhi' },
    { country: country, name: 'Puducherry' }
  ]
)

andhra_pradesh     = State.find_by(name: 'Andhra Pradesh')
arunachal_pradesh  = State.find_by(name: 'Arunachal Pradesh')
assam              = State.find_by(name: 'Assam')
bihar              = State.find_by(name: 'Bihar')
chhattisgarh       = State.find_by(name: 'Chhattisgarh')
goa                = State.find_by(name: 'Goa')
gujarat            = State.find_by(name: 'Gujarat')
haryana            = State.find_by(name: 'Haryana')
himachal_pradesh   = State.find_by(name: 'Himachal Pradesh')
jammu_kashmir      = State.find_by(name: 'Jammu and Kashmir')
jharkhand          = State.find_by(name: 'Jharkhand')
karnataka          = State.find_by(name: 'Karnataka')
kerala             = State.find_by(name: 'Kerala')
madhya_pradesh     = State.find_by(name: 'Madhya Pradesh')
maharashtra        = State.find_by(name: 'Maharashtra')
manipur            = State.find_by(name: 'Manipur')
meghalaya          = State.find_by(name: 'Meghalaya')
mizoram            = State.find_by(name: 'Mizoram')
nagaland           = State.find_by(name: 'Nagaland')
odisha             = State.find_by(name: 'Odisha')
punjab             = State.find_by(name: 'Punjab')
rajasthan          = State.find_by(name: 'Rajasthan')
sikkim             = State.find_by(name: 'Sikkim')
tamil_nadu         = State.find_by(name: 'Tamil Nadu')
telangana          = State.find_by(name: 'Telangana')
tripura            = State.find_by(name: 'Tripura')
uttar_pradesh      = State.find_by(name: 'Uttar Pradesh')
uttarakhand        = State.find_by(name: 'Uttarakhand')
west_bengal        = State.find_by(name: 'West Bengal')
andaman_nicobar    = State.find_by(name: 'Andaman and Nicobar')
chandigarh         = State.find_by(name: 'Chandigarh')
dadra_nagar_haveli = State.find_by(name: 'Dadra Nagar Haveli')
daman_diu          = State.find_by(name: 'Daman and Diu')
delhi              = State.find_by(name: 'Delhi')
lakshadweep        = State.find_by(name: 'Lakshadweep')
ladakh             = State.find_by(name: 'Ladakh')
puducherry         = State.find_by(name: 'Puducherry')

District.create(
  [
    { state: andhra_pradesh, name: 'Anantapur' },
    { state: andhra_pradesh, name: 'Chittoor' },
    { state: andhra_pradesh, name: 'East Godavari' },
    { state: andhra_pradesh, name: 'Guntur' },
    { state: andhra_pradesh, name: 'Kadapa' },
    { state: andhra_pradesh, name: 'Krishna' },
    { state: andhra_pradesh, name: 'Kurnool' },
    { state: andhra_pradesh, name: 'Nellore' },
    { state: andhra_pradesh, name: 'Prakasam' },
    { state: andhra_pradesh, name: 'Srikakulam' },
    { state: andhra_pradesh, name: 'Visakhapatnam' },
    { state: andhra_pradesh, name: 'Vizianagaram' },
    { state: andhra_pradesh, name: 'West Godavari' },
    { state: arunachal_pradesh, name: 'Anjaw' },
    { state: arunachal_pradesh, name: 'Siang' },
    { state: arunachal_pradesh, name: 'Changlang' },
    { state: arunachal_pradesh, name: 'Dibang Valley' },
    { state: arunachal_pradesh, name: 'East Kameng' },
    { state: arunachal_pradesh, name: 'East Siang' },
    { state: arunachal_pradesh, name: 'Kamle' },
    { state: arunachal_pradesh, name: 'Kra Daadi' },
    { state: arunachal_pradesh, name: 'Kurung Kumey' },
    { state: arunachal_pradesh, name: 'Lepa Rada' },
    { state: arunachal_pradesh, name: 'Lohit' },
    { state: arunachal_pradesh, name: 'Longding' },
    { state: arunachal_pradesh, name: 'Lower Dibang Valley' },
    { state: arunachal_pradesh, name: 'Lower Siang' },
    { state: arunachal_pradesh, name: 'Lower Subansiri' },
    { state: arunachal_pradesh, name: 'Namsai' },
    { state: arunachal_pradesh, name: 'Pakke Kessang' },
    { state: arunachal_pradesh, name: 'Papum Pare' },
    { state: arunachal_pradesh, name: 'Shi Yomi' },
    { state: arunachal_pradesh, name: 'Tawang' },
    { state: arunachal_pradesh, name: 'Tirap' },
    { state: arunachal_pradesh, name: 'Upper Siang' },
    { state: arunachal_pradesh, name: 'Upper Subansiri' },
    { state: arunachal_pradesh, name: 'West Kameng' },
    { state: arunachal_pradesh, name: 'West Siang' },
    { state: assam, name: 'Bajali' },
    { state: assam, name: 'Baksa' },
    { state: assam, name: 'Barpeta' },
    { state: assam, name: 'Biswanath' },
    { state: assam, name: 'Bongaigaon' },
    { state: assam, name: 'Cachar' },
    { state: assam, name: 'Charaideo' },
    { state: assam, name: 'Chirang' },
    { state: assam, name: 'Darrang' },
    { state: assam, name: 'Dhemaji' },
    { state: assam, name: 'Dhubri' },
    { state: assam, name: 'Dibrugarh' },
    { state: assam, name: 'Dima Hasao' },
    { state: assam, name: 'Goalpara' },
    { state: assam, name: 'Golaghat' },
    { state: assam, name: 'Hailakandi' },
    { state: assam, name: 'Hojai' },
    { state: assam, name: 'Jorhat' },
    { state: assam, name: 'Kamrup' },
    { state: assam, name: 'Kamrup Metropolitan' },
    { state: assam, name: 'Karbi Anglong' },
    { state: assam, name: 'Karimganj' },
    { state: assam, name: 'Kokrajhar' },
    { state: assam, name: 'Lakhimpur' },
    { state: assam, name: 'Majuli' },
    { state: assam, name: 'Morigaon' },
    { state: assam, name: 'Nagaon' },
    { state: assam, name: 'Nalbari' },
    { state: assam, name: 'Sivasagar' },
    { state: assam, name: 'Sonitpur' },
    { state: assam, name: 'South Salmara-Mankachar' },
    { state: assam, name: 'Tinsukia' },
    { state: assam, name: 'Udalguri' },
    { state: assam, name: 'West Karbi Anglong' },
    { state: bihar, name: 'Araria' },
    { state: bihar, name: 'Arwal' },
    { state: bihar, name: 'Aurangabad' },
    { state: bihar, name: 'Banka' },
    { state: bihar, name: 'Begusarai' },
    { state: bihar, name: 'Bhagalpur' },
    { state: bihar, name: 'Bhojpur' },
    { state: bihar, name: 'Buxar' },
    { state: bihar, name: 'Darbhanga' },
    { state: bihar, name: 'East Champaran' },
    { state: bihar, name: 'Gaya' },
    { state: bihar, name: 'Gopalganj' },
    { state: bihar, name: 'Jamui' },
    { state: bihar, name: 'Jehanabad' },
    { state: bihar, name: 'Kaimur' },
    { state: bihar, name: 'Katihar' },
    { state: bihar, name: 'Khagaria' },
    { state: bihar, name: 'Kishanganj' },
    { state: bihar, name: 'Lakhisarai' },
    { state: bihar, name: 'Madhepura' },
    { state: bihar, name: 'Madhubani' },
    { state: bihar, name: 'Munger' },
    { state: bihar, name: 'Muzaffarpur' },
    { state: bihar, name: 'Nalanda' },
    { state: bihar, name: 'Nawada' },
    { state: bihar, name: 'Patna' },
    { state: bihar, name: 'Purnia' },
    { state: bihar, name: 'Rohtas' },
    { state: bihar, name: 'Saharsa' },
    { state: bihar, name: 'Samastipur' },
    { state: bihar, name: 'Saran' },
    { state: bihar, name: 'Sheikhpura' },
    { state: bihar, name: 'Sheohar' },
    { state: bihar, name: 'Sitamarhi' },
    { state: bihar, name: 'Siwan' },
    { state: bihar, name: 'Supaul' },
    { state: bihar, name: 'Vaishali' },
    { state: bihar, name: 'West Champaran' },
    { state: chhattisgarh, name: 'Balod' },
    { state: chhattisgarh, name: 'Baloda Bazar' },
    { state: chhattisgarh, name: 'Balrampur Ramanujganj' },
    { state: chhattisgarh, name: 'Bastar' },
    { state: chhattisgarh, name: 'Bemetara' },
    { state: chhattisgarh, name: 'Bijapur' },
    { state: chhattisgarh, name: 'Bilaspur' },
    { state: chhattisgarh, name: 'Dantewada' },
    { state: chhattisgarh, name: 'Dhamtari' },
    { state: chhattisgarh, name: 'Durg' },
    { state: chhattisgarh, name: 'Gariaband' },
    { state: chhattisgarh, name: 'Gaurela Pendra Marwahi' },
    { state: chhattisgarh, name: 'Janjgir Champa' },
    { state: chhattisgarh, name: 'Jashpur' },
    { state: chhattisgarh, name: 'Kabirdham' },
    { state: chhattisgarh, name: 'Kanker' },
    { state: chhattisgarh, name: 'Kondagaon' },
    { state: chhattisgarh, name: 'Korba' },
    { state: chhattisgarh, name: 'Koriya' },
    { state: chhattisgarh, name: 'Mahasamund' },
    { state: chhattisgarh, name: 'Mungeli' },
    { state: chhattisgarh, name: 'Narayanpur' },
    { state: chhattisgarh, name: 'Raigarh' },
    { state: chhattisgarh, name: 'Raipur' },
    { state: chhattisgarh, name: 'Rajnandgaon' },
    { state: chhattisgarh, name: 'Sukma' },
    { state: chhattisgarh, name: 'Surajpur' },
    { state: chhattisgarh, name: 'Surguja' },
    { state: goa, name: 'North Goa' },
    { state: goa, name: 'South Goa' },
    { state: gujarat, name: 'Ahmedabad' },
    { state: gujarat, name: 'Amreli' },
    { state: gujarat, name: 'Anand' },
    { state: gujarat, name: 'Aravalli' },
    { state: gujarat, name: 'Banaskantha' },
    { state: gujarat, name: 'Bharuch' },
    { state: gujarat, name: 'Bhavnagar' },
    { state: gujarat, name: 'Botad' },
    { state: gujarat, name: 'Chhota Udaipur' },
    { state: gujarat, name: 'Dahod' },
    { state: gujarat, name: 'Dang' },
    { state: gujarat, name: 'Devbhoomi Dwarka' },
    { state: gujarat, name: 'Gandhinagar' },
    { state: gujarat, name: 'Gir Somnath' },
    { state: gujarat, name: 'Jamnagar' },
    { state: gujarat, name: 'Junagadh' },
    { state: gujarat, name: 'Kheda' },
    { state: gujarat, name: 'Kutch' },
    { state: gujarat, name: 'Mahisagar' },
    { state: gujarat, name: 'Mehsana' },
    { state: gujarat, name: 'Morbi' },
    { state: gujarat, name: 'Narmada' },
    { state: gujarat, name: 'Navsari' },
    { state: gujarat, name: 'Panchmahal' },
    { state: gujarat, name: 'Patan' },
    { state: gujarat, name: 'Porbandar' },
    { state: gujarat, name: 'Rajkot' },
    { state: gujarat, name: 'Sabarkantha' },
    { state: gujarat, name: 'Surat' },
    { state: gujarat, name: 'Surendranagar' },
    { state: gujarat, name: 'Tapi' },
    { state: gujarat, name: 'Vadodara' },
    { state: gujarat, name: 'Valsad' },
    { state: haryana, name: 'Ambala' },
    { state: haryana, name: 'Bhiwani' },
    { state: haryana, name: 'Charkhi Dadri' },
    { state: haryana, name: 'Faridabad' },
    { state: haryana, name: 'Fatehabad' },
    { state: haryana, name: 'Gurugram' },
    { state: haryana, name: 'Hisar' },
    { state: haryana, name: 'Jhajjar' },
    { state: haryana, name: 'Jind' },
    { state: haryana, name: 'Kaithal' },
    { state: haryana, name: 'Karnal' },
    { state: haryana, name: 'Kurukshetra' },
    { state: haryana, name: 'Mahendragarh' },
    { state: haryana, name: 'Mewat' },
    { state: haryana, name: 'Palwal' },
    { state: haryana, name: 'Panchkula' },
    { state: haryana, name: 'Panipat' },
    { state: haryana, name: 'Rewari' },
    { state: haryana, name: 'Rohtak' },
    { state: haryana, name: 'Sirsa' },
    { state: haryana, name: 'Sonipat' },
    { state: haryana, name: 'Yamunanagar' },
    { state: himachal_pradesh, name: 'Bilaspur' },
    { state: himachal_pradesh, name: 'Chamba' },
    { state: himachal_pradesh, name: 'Hamirpur' },
    { state: himachal_pradesh, name: 'Kangra' },
    { state: himachal_pradesh, name: 'Kinnaur' },
    { state: himachal_pradesh, name: 'Kullu' },
    { state: himachal_pradesh, name: 'Lahaul Spiti' },
    { state: himachal_pradesh, name: 'Mandi' },
    { state: himachal_pradesh, name: 'Shimla' },
    { state: himachal_pradesh, name: 'Sirmaur' },
    { state: himachal_pradesh, name: 'Solan' },
    { state: himachal_pradesh, name: 'Una' },
    { state: jammu_kashmir, name: 'Anantnag' },
    { state: jammu_kashmir, name: 'Bandipora' },
    { state: jammu_kashmir, name: 'Baramulla' },
    { state: jammu_kashmir, name: 'Budgam' },
    { state: jammu_kashmir, name: 'Doda' },
    { state: jammu_kashmir, name: 'Ganderbal' },
    { state: jammu_kashmir, name: 'Jammu' },
    { state: jammu_kashmir, name: 'Kathua' },
    { state: jammu_kashmir, name: 'Kishtwar' },
    { state: jammu_kashmir, name: 'Kulgam' },
    { state: jammu_kashmir, name: 'Kupwara' },
    { state: jammu_kashmir, name: 'Poonch' },
    { state: jammu_kashmir, name: 'Pulwama' },
    { state: jammu_kashmir, name: 'Rajouri' },
    { state: jammu_kashmir, name: 'Ramban' },
    { state: jammu_kashmir, name: 'Reasi' },
    { state: jammu_kashmir, name: 'Samba' },
    { state: jammu_kashmir, name: 'Shopian' },
    { state: jammu_kashmir, name: 'Srinagar' },
    { state: jammu_kashmir, name: 'Udhampur' },
    { state: jharkhand, name: 'Bokaro' },
    { state: jharkhand, name: 'Chatra' },
    { state: jharkhand, name: 'Deoghar' },
    { state: jharkhand, name: 'Dhanbad' },
    { state: jharkhand, name: 'Dumka' },
    { state: jharkhand, name: 'East Singhbhum' },
    { state: jharkhand, name: 'Garhwa' },
    { state: jharkhand, name: 'Giridih' },
    { state: jharkhand, name: 'Godda' },
    { state: jharkhand, name: 'Gumla' },
    { state: jharkhand, name: 'Hazaribagh' },
    { state: jharkhand, name: 'Jamtara' },
    { state: jharkhand, name: 'Khunti' },
    { state: jharkhand, name: 'Koderma' },
    { state: jharkhand, name: 'Latehar' },
    { state: jharkhand, name: 'Lohardaga' },
    { state: jharkhand, name: 'Pakur' },
    { state: jharkhand, name: 'Palamu' },
    { state: jharkhand, name: 'Ramgarh' },
    { state: jharkhand, name: 'Ranchi' },
    { state: jharkhand, name: 'Sahebganj' },
    { state: jharkhand, name: 'Seraikela Kharsawan' },
    { state: jharkhand, name: 'Simdega' },
    { state: jharkhand, name: 'West Singhbhum' },
    { state: karnataka, name: 'Bagalkot' },
    { state: karnataka, name: 'Bangalore Rural' },
    { state: karnataka, name: 'Bangalore Urban' },
    { state: karnataka, name: 'Belgaum' },
    { state: karnataka, name: 'Bellary' },
    { state: karnataka, name: 'Bidar' },
    { state: karnataka, name: 'Chamarajanagar' },
    { state: karnataka, name: 'Chikkaballapur' },
    { state: karnataka, name: 'Chikkamagaluru' },
    { state: karnataka, name: 'Chitradurga' },
    { state: karnataka, name: 'Dakshina Kannada' },
    { state: karnataka, name: 'Davanagere' },
    { state: karnataka, name: 'Dharwad' },
    { state: karnataka, name: 'Gadag' },
    { state: karnataka, name: 'Gulbarga' },
    { state: karnataka, name: 'Hassan' },
    { state: karnataka, name: 'Haveri' },
    { state: karnataka, name: 'Kodagu' },
    { state: karnataka, name: 'Kolar' },
    { state: karnataka, name: 'Koppal' },
    { state: karnataka, name: 'Mandya' },
    { state: karnataka, name: 'Mysore' },
    { state: karnataka, name: 'Raichur' },
    { state: karnataka, name: 'Ramanagara' },
    { state: karnataka, name: 'Shimoga' },
    { state: karnataka, name: 'Tumkur' },
    { state: karnataka, name: 'Udupi' },
    { state: karnataka, name: 'Uttara Kannada' },
    { state: karnataka, name: 'Vijayapura' },
    { state: karnataka, name: 'Yadgir' },
    { state: kerala, name: 'Alappuzha' },
    { state: kerala, name: 'Ernakulam' },
    { state: kerala, name: 'Idukki' },
    { state: kerala, name: 'Kannur' },
    { state: kerala, name: 'Kasaragod' },
    { state: kerala, name: 'Kollam' },
    { state: kerala, name: 'Kottayam' },
    { state: kerala, name: 'Kozhikode' },
    { state: kerala, name: 'Malappuram' },
    { state: kerala, name: 'Palakkad' },
    { state: kerala, name: 'Pathanamthitta' },
    { state: kerala, name: 'Thiruvananthapuram' },
    { state: kerala, name: 'Thrissur' },
    { state: kerala, name: 'Wayanad' },
    { state: madhya_pradesh, name: 'Agar Malwa' },
    { state: madhya_pradesh, name: 'Alirajpur' },
    { state: madhya_pradesh, name: 'Anuppur' },
    { state: madhya_pradesh, name: 'Ashoknagar' },
    { state: madhya_pradesh, name: 'Balaghat' },
    { state: madhya_pradesh, name: 'Barwani' },
    { state: madhya_pradesh, name: 'Betul' },
    { state: madhya_pradesh, name: 'Bhind' },
    { state: madhya_pradesh, name: 'Bhopal' },
    { state: madhya_pradesh, name: 'Burhanpur' },
    { state: madhya_pradesh, name: 'Chachaura' },
    { state: madhya_pradesh, name: 'Chhatarpur' },
    { state: madhya_pradesh, name: 'Chhindwara' },
    { state: madhya_pradesh, name: 'Damoh' },
    { state: madhya_pradesh, name: 'Datia' },
    { state: madhya_pradesh, name: 'Dewas' },
    { state: madhya_pradesh, name: 'Dhar' },
    { state: madhya_pradesh, name: 'Dindori' },
    { state: madhya_pradesh, name: 'Guna' },
    { state: madhya_pradesh, name: 'Gwalior' },
    { state: madhya_pradesh, name: 'Harda' },
    { state: madhya_pradesh, name: 'Hoshangabad' },
    { state: madhya_pradesh, name: 'Indore' },
    { state: madhya_pradesh, name: 'Jabalpur' },
    { state: madhya_pradesh, name: 'Jhabua' },
    { state: madhya_pradesh, name: 'Katni' },
    { state: madhya_pradesh, name: 'Khandwa' },
    { state: madhya_pradesh, name: 'Khargone' },
    { state: madhya_pradesh, name: 'Maihar' },
    { state: madhya_pradesh, name: 'Mandla' },
    { state: madhya_pradesh, name: 'Mandsaur' },
    { state: madhya_pradesh, name: 'Morena' },
    { state: madhya_pradesh, name: 'Nagda' },
    { state: madhya_pradesh, name: 'Narsinghpur' },
    { state: madhya_pradesh, name: 'Neemuch' },
    { state: madhya_pradesh, name: 'Niwari' },
    { state: madhya_pradesh, name: 'Panna' },
    { state: madhya_pradesh, name: 'Raisen' },
    { state: madhya_pradesh, name: 'Rajgarh' },
    { state: madhya_pradesh, name: 'Ratlam' },
    { state: madhya_pradesh, name: 'Rewa' },
    { state: madhya_pradesh, name: 'Sagar' },
    { state: madhya_pradesh, name: 'Satna' },
    { state: madhya_pradesh, name: 'Sehore' },
    { state: madhya_pradesh, name: 'Seoni' },
    { state: madhya_pradesh, name: 'Shahdol' },
    { state: madhya_pradesh, name: 'Shajapur' },
    { state: madhya_pradesh, name: 'Sheopur' },
    { state: madhya_pradesh, name: 'Shivpuri' },
    { state: madhya_pradesh, name: 'Sidhi' },
    { state: madhya_pradesh, name: 'Singrauli' },
    { state: madhya_pradesh, name: 'Tikamgarh' },
    { state: madhya_pradesh, name: 'Ujjain' },
    { state: madhya_pradesh, name: 'Umaria' },
    { state: madhya_pradesh, name: 'Vidisha' },
    { state: maharashtra, name: 'Ahmednagar' },
    { state: maharashtra, name: 'Akola' },
    { state: maharashtra, name: 'Amravati' },
    { state: maharashtra, name: 'Aurangabad' },
    { state: maharashtra, name: 'Beed' },
    { state: maharashtra, name: 'Bhandara' },
    { state: maharashtra, name: 'Buldhana' },
    { state: maharashtra, name: 'Chandrapur' },
    { state: maharashtra, name: 'Dhule' },
    { state: maharashtra, name: 'Gadchiroli' },
    { state: maharashtra, name: 'Gondia' },
    { state: maharashtra, name: 'Hingoli' },
    { state: maharashtra, name: 'Jalgaon' },
    { state: maharashtra, name: 'Jalna' },
    { state: maharashtra, name: 'Kolhapur' },
    { state: maharashtra, name: 'Latur' },
    { state: maharashtra, name: 'Mumbai City' },
    { state: maharashtra, name: 'Mumbai Suburban' },
    { state: maharashtra, name: 'Nagpur' },
    { state: maharashtra, name: 'Nanded' },
    { state: maharashtra, name: 'Nandurbar' },
    { state: maharashtra, name: 'Nashik' },
    { state: maharashtra, name: 'Osmanabad' },
    { state: maharashtra, name: 'Palghar' },
    { state: maharashtra, name: 'Parbhani' },
    { state: maharashtra, name: 'Pune' },
    { state: maharashtra, name: 'Raigad' },
    { state: maharashtra, name: 'Ratnagiri' },
    { state: maharashtra, name: 'Sangli' },
    { state: maharashtra, name: 'Satara' },
    { state: maharashtra, name: 'Sindhudurg' },
    { state: maharashtra, name: 'Solapur' },
    { state: maharashtra, name: 'Thane' },
    { state: maharashtra, name: 'Wardha' },
    { state: maharashtra, name: 'Washim' },
    { state: maharashtra, name: 'Yavatmal' },
    { state: manipur, name: 'Bishnupur' },
    { state: manipur, name: 'Chandel' },
    { state: manipur, name: 'Churachandpur' },
    { state: manipur, name: 'Imphal East' },
    { state: manipur, name: 'Imphal West' },
    { state: manipur, name: 'Jiribam' },
    { state: manipur, name: 'Kakching' },
    { state: manipur, name: 'Kamjong' },
    { state: manipur, name: 'Kangpokpi' },
    { state: manipur, name: 'Noney' },
    { state: manipur, name: 'Pherzawl' },
    { state: manipur, name: 'Senapati' },
    { state: manipur, name: 'Tamenglong' },
    { state: manipur, name: 'Tengnoupal' },
    { state: manipur, name: 'Thoubal' },
    { state: manipur, name: 'Ukhrul' },
    { state: meghalaya, name: 'East Garo Hills' },
    { state: meghalaya, name: 'East Jaintia Hills' },
    { state: meghalaya, name: 'East Khasi Hills' },
    { state: meghalaya, name: 'North Garo Hills' },
    { state: meghalaya, name: 'Ri Bhoi' },
    { state: meghalaya, name: 'South Garo Hills' },
    { state: meghalaya, name: 'South West Garo Hills' },
    { state: meghalaya, name: 'South West Khasi Hills' },
    { state: meghalaya, name: 'West Garo Hills' },
    { state: meghalaya, name: 'West Jaintia Hills' },
    { state: meghalaya, name: 'West Khasi Hills' },
    { state: mizoram, name: 'Aizawl' },
    { state: mizoram, name: 'Champhai' },
    { state: mizoram, name: 'Hnahthial' },
    { state: mizoram, name: 'Khawzawl' },
    { state: mizoram, name: 'Kolasib' },
    { state: mizoram, name: 'Lawngtlai' },
    { state: mizoram, name: 'Lunglei' },
    { state: mizoram, name: 'Mamit' },
    { state: mizoram, name: 'Saiha' },
    { state: mizoram, name: 'Saitual' },
    { state: mizoram, name: 'Serchhip' },
    { state: nagaland, name: 'Mon' },
    { state: nagaland, name: 'Dimapur' },
    { state: nagaland, name: 'Kiphire' },
    { state: nagaland, name: 'Kohima' },
    { state: nagaland, name: 'Longleng' },
    { state: nagaland, name: 'Mokokchung' },
    { state: nagaland, name: 'Noklak' },
    { state: nagaland, name: 'Peren' },
    { state: nagaland, name: 'Phek' },
    { state: nagaland, name: 'Tuensang' },
    { state: nagaland, name: 'Wokha' },
    { state: nagaland, name: 'Zunheboto' },
    { state: odisha, name: 'Angul' },
    { state: odisha, name: 'Balangir' },
    { state: odisha, name: 'Balasore' },
    { state: odisha, name: 'Bargarh' },
    { state: odisha, name: 'Bhadrak' },
    { state: odisha, name: 'Boudh' },
    { state: odisha, name: 'Cuttack' },
    { state: odisha, name: 'Debagarh' },
    { state: odisha, name: 'Dhenkanal' },
    { state: odisha, name: 'Gajapati' },
    { state: odisha, name: 'Ganjam' },
    { state: odisha, name: 'Jagatsinghpur' },
    { state: odisha, name: 'Jajpur' },
    { state: odisha, name: 'Jharsuguda' },
    { state: odisha, name: 'Kalahandi' },
    { state: odisha, name: 'Kandhamal' },
    { state: odisha, name: 'Kendrapara' },
    { state: odisha, name: 'Kendujhar' },
    { state: odisha, name: 'Khordha' },
    { state: odisha, name: 'Koraput' },
    { state: odisha, name: 'Malkangiri' },
    { state: odisha, name: 'Mayurbhanj' },
    { state: odisha, name: 'Nabarangpur' },
    { state: odisha, name: 'Nayagarh' },
    { state: odisha, name: 'Nuapada' },
    { state: odisha, name: 'Puri' },
    { state: odisha, name: 'Rayagada' },
    { state: odisha, name: 'Sambalpur' },
    { state: odisha, name: 'Subarnapur' },
    { state: odisha, name: 'Sundergarh' },
    { state: punjab, name: 'Amritsar' },
    { state: punjab, name: 'Barnala' },
    { state: punjab, name: 'Bathinda' },
    { state: punjab, name: 'Faridkot' },
    { state: punjab, name: 'Fatehgarh Sahib' },
    { state: punjab, name: 'Fazilka' },
    { state: punjab, name: 'Firozpur' },
    { state: punjab, name: 'Gurdaspur' },
    { state: punjab, name: 'Hoshiarpur' },
    { state: punjab, name: 'Jalandhar' },
    { state: punjab, name: 'Kapurthala' },
    { state: punjab, name: 'Ludhiana' },
    { state: punjab, name: 'Mansa' },
    { state: punjab, name: 'Moga' },
    { state: punjab, name: 'Mohali' },
    { state: punjab, name: 'Muktsar' },
    { state: punjab, name: 'Pathankot' },
    { state: punjab, name: 'Patiala' },
    { state: punjab, name: 'Rupnagar' },
    { state: punjab, name: 'Sangrur' },
    { state: punjab, name: 'Shaheed Bhagat Singh Nagar' },
    { state: punjab, name: 'Tarn Taran' },
    { state: rajasthan, name: 'Ajmer' },
    { state: rajasthan, name: 'Alwar' },
    { state: rajasthan, name: 'Banswara' },
    { state: rajasthan, name: 'Baran' },
    { state: rajasthan, name: 'Barmer' },
    { state: rajasthan, name: 'Bharatpur' },
    { state: rajasthan, name: 'Bhilwara' },
    { state: rajasthan, name: 'Bikaner' },
    { state: rajasthan, name: 'Bundi' },
    { state: rajasthan, name: 'Chittorgarh' },
    { state: rajasthan, name: 'Churu' },
    { state: rajasthan, name: 'Dausa' },
    { state: rajasthan, name: 'Dholpur' },
    { state: rajasthan, name: 'Dungarpur' },
    { state: rajasthan, name: 'Sri Ganganagar' },
    { state: rajasthan, name: 'Hanumangarh' },
    { state: rajasthan, name: 'Jaipur' },
    { state: rajasthan, name: 'Jaisalmer' },
    { state: rajasthan, name: 'Jalore' },
    { state: rajasthan, name: 'Jhalawar' },
    { state: rajasthan, name: 'Jhunjhunu' },
    { state: rajasthan, name: 'Jodhpur' },
    { state: rajasthan, name: 'Karauli' },
    { state: rajasthan, name: 'Kota' },
    { state: rajasthan, name: 'Nagaur' },
    { state: rajasthan, name: 'Pali' },
    { state: rajasthan, name: 'Pratapgarh' },
    { state: rajasthan, name: 'Rajsamand' },
    { state: rajasthan, name: 'Sawai Madhopur' },
    { state: rajasthan, name: 'Sikar' },
    { state: rajasthan, name: 'Sirohi' },
    { state: rajasthan, name: 'Tonk' },
    { state: rajasthan, name: 'Udaipur' },
    { state: sikkim, name: 'East Sikkim' },
    { state: sikkim, name: 'North Sikkim' },
    { state: sikkim, name: 'South Sikkim' },
    { state: sikkim, name: 'West Sikkim' },
    { state: tamil_nadu, name: 'Ariyalur' },
    { state: tamil_nadu, name: 'Chengalpattu' },
    { state: tamil_nadu, name: 'Chennai' },
    { state: tamil_nadu, name: 'Coimbatore' },
    { state: tamil_nadu, name: 'Cuddalore' },
    { state: tamil_nadu, name: 'Dharmapuri' },
    { state: tamil_nadu, name: 'Dindigul' },
    { state: tamil_nadu, name: 'Erode' },
    { state: tamil_nadu, name: 'Kallakurichi' },
    { state: tamil_nadu, name: 'Kanchipuram' },
    { state: tamil_nadu, name: 'Kanyakumari' },
    { state: tamil_nadu, name: 'Karur' },
    { state: tamil_nadu, name: 'Krishnagiri' },
    { state: tamil_nadu, name: 'Madurai' },
    { state: tamil_nadu, name: 'Mayiladuthurai' },
    { state: tamil_nadu, name: 'Nagapattinam' },
    { state: tamil_nadu, name: 'Namakkal' },
    { state: tamil_nadu, name: 'Nilgiris' },
    { state: tamil_nadu, name: 'Perambalur' },
    { state: tamil_nadu, name: 'Pudukkottai' },
    { state: tamil_nadu, name: 'Ramanathapuram' },
    { state: tamil_nadu, name: 'Ranipet' },
    { state: tamil_nadu, name: 'Salem' },
    { state: tamil_nadu, name: 'Sivaganga' },
    { state: tamil_nadu, name: 'Tenkasi' },
    { state: tamil_nadu, name: 'Thanjavur' },
    { state: tamil_nadu, name: 'Theni' },
    { state: tamil_nadu, name: 'Thoothukudi' },
    { state: tamil_nadu, name: 'Tiruchirappalli' },
    { state: tamil_nadu, name: 'Tirunelveli' },
    { state: tamil_nadu, name: 'Tirupattur' },
    { state: tamil_nadu, name: 'Tiruppur' },
    { state: tamil_nadu, name: 'Tiruvallur' },
    { state: tamil_nadu, name: 'Tiruvannamalai' },
    { state: tamil_nadu, name: 'Tiruvarur' },
    { state: tamil_nadu, name: 'Vellore' },
    { state: tamil_nadu, name: 'Viluppuram' },
    { state: tamil_nadu, name: 'Virudhunagar' },
    { state: telangana, name: 'Adilabad' },
    { state: telangana, name: 'Bhadradri Kothagudem' },
    { state: telangana, name: 'Hyderabad' },
    { state: telangana, name: 'Jagtial' },
    { state: telangana, name: 'Jangaon' },
    { state: telangana, name: 'Jayashankar Bhupalpally' },
    { state: telangana, name: 'Jogulamba Gadwal' },
    { state: telangana, name: 'Kamareddy' },
    { state: telangana, name: 'Karimnagar' },
    { state: telangana, name: 'Khammam' },
    { state: telangana, name: 'Komaram Bheem' },
    { state: telangana, name: 'Mahabubabad' },
    { state: telangana, name: 'Mahbubnagar' },
    { state: telangana, name: 'Mancherial' },
    { state: telangana, name: 'Medak' },
    { state: telangana, name: 'Medchal' },
    { state: telangana, name: 'Mulugu' },
    { state: telangana, name: 'Nagarkurnool' },
    { state: telangana, name: 'Nalgonda' },
    { state: telangana, name: 'Narayanpet' },
    { state: telangana, name: 'Nirmal' },
    { state: telangana, name: 'Nizamabad' },
    { state: telangana, name: 'Peddapalli' },
    { state: telangana, name: 'Rajanna Sircilla' },
    { state: telangana, name: 'Ranga Reddy' },
    { state: telangana, name: 'Sangareddy' },
    { state: telangana, name: 'Siddipet' },
    { state: telangana, name: 'Suryapet' },
    { state: telangana, name: 'Vikarabad' },
    { state: telangana, name: 'Wanaparthy' },
    { state: telangana, name: 'Warangal Rural' },
    { state: telangana, name: 'Warangal Urban' },
    { state: telangana, name: 'Yadadri Bhuvanagiri' },
    { state: tripura, name: 'Dhalai' },
    { state: tripura, name: 'Gomati' },
    { state: tripura, name: 'Khowai' },
    { state: tripura, name: 'North Tripura' },
    { state: tripura, name: 'Sepahijala' },
    { state: tripura, name: 'South Tripura' },
    { state: tripura, name: 'Unakoti' },
    { state: tripura, name: 'West Tripura' },
    { state: uttar_pradesh, name: 'Agra' },
    { state: uttar_pradesh, name: 'Aligarh' },
    { state: uttar_pradesh, name: 'Prayagraj' },
    { state: uttar_pradesh, name: 'Ambedkar Nagar' },
    { state: uttar_pradesh, name: 'Amethi' },
    { state: uttar_pradesh, name: 'Amroha' },
    { state: uttar_pradesh, name: 'Auraiya' },
    { state: uttar_pradesh, name: 'Azamgarh' },
    { state: uttar_pradesh, name: 'Baghpat' },
    { state: uttar_pradesh, name: 'Bahraich' },
    { state: uttar_pradesh, name: 'Ballia' },
    { state: uttar_pradesh, name: 'Balrampur' },
    { state: uttar_pradesh, name: 'Banda' },
    { state: uttar_pradesh, name: 'Barabanki' },
    { state: uttar_pradesh, name: 'Bareilly' },
    { state: uttar_pradesh, name: 'Basti' },
    { state: uttar_pradesh, name: 'Bhadohi' },
    { state: uttar_pradesh, name: 'Bijnor' },
    { state: uttar_pradesh, name: 'Budaun' },
    { state: uttar_pradesh, name: 'Bulandshahr' },
    { state: uttar_pradesh, name: 'Chandauli' },
    { state: uttar_pradesh, name: 'Chitrakoot' },
    { state: uttar_pradesh, name: 'Deoria' },
    { state: uttar_pradesh, name: 'Etah' },
    { state: uttar_pradesh, name: 'Etawah' },
    { state: uttar_pradesh, name: 'Ayodhya' },
    { state: uttar_pradesh, name: 'Farrukhabad' },
    { state: uttar_pradesh, name: 'Fatehpur' },
    { state: uttar_pradesh, name: 'Firozabad' },
    { state: uttar_pradesh, name: 'Gautam Buddha Nagar' },
    { state: uttar_pradesh, name: 'Ghaziabad' },
    { state: uttar_pradesh, name: 'Ghazipur' },
    { state: uttar_pradesh, name: 'Gonda' },
    { state: uttar_pradesh, name: 'Gorakhpur' },
    { state: uttar_pradesh, name: 'Hamirpur' },
    { state: uttar_pradesh, name: 'Hapur' },
    { state: uttar_pradesh, name: 'Hardoi' },
    { state: uttar_pradesh, name: 'Hathras' },
    { state: uttar_pradesh, name: 'Jalaun' },
    { state: uttar_pradesh, name: 'Jaunpur' },
    { state: uttar_pradesh, name: 'Jhansi' },
    { state: uttar_pradesh, name: 'Kannauj' },
    { state: uttar_pradesh, name: 'Kanpur Dehat' },
    { state: uttar_pradesh, name: 'Kanpur Nagar' },
    { state: uttar_pradesh, name: 'Kasganj' },
    { state: uttar_pradesh, name: 'Kaushambi' },
    { state: uttar_pradesh, name: 'Kheri' },
    { state: uttar_pradesh, name: 'Kushinagar' },
    { state: uttar_pradesh, name: 'Lalitpur' },
    { state: uttar_pradesh, name: 'Lucknow' },
    { state: uttar_pradesh, name: 'Maharajganj' },
    { state: uttar_pradesh, name: 'Mahoba' },
    { state: uttar_pradesh, name: 'Mainpuri' },
    { state: uttar_pradesh, name: 'Mathura' },
    { state: uttar_pradesh, name: 'Mau' },
    { state: uttar_pradesh, name: 'Meerut' },
    { state: uttar_pradesh, name: 'Mirzapur' },
    { state: uttar_pradesh, name: 'Moradabad' },
    { state: uttar_pradesh, name: 'Muzaffarnagar' },
    { state: uttar_pradesh, name: 'Pilibhit' },
    { state: uttar_pradesh, name: 'Pratapgarh' },
    { state: uttar_pradesh, name: 'Raebareli' },
    { state: uttar_pradesh, name: 'Rampur' },
    { state: uttar_pradesh, name: 'Saharanpur' },
    { state: uttar_pradesh, name: 'Sambhal' },
    { state: uttar_pradesh, name: 'Sant Kabir Nagar' },
    { state: uttar_pradesh, name: 'Shahjahanpur' },
    { state: uttar_pradesh, name: 'Shamli' },
    { state: uttar_pradesh, name: 'Shravasti' },
    { state: uttar_pradesh, name: 'Siddharthnagar' },
    { state: uttar_pradesh, name: 'Sitapur' },
    { state: uttar_pradesh, name: 'Sonbhadra' },
    { state: uttar_pradesh, name: 'Sultanpur' },
    { state: uttar_pradesh, name: 'Unnao' },
    { state: uttar_pradesh, name: 'Varanasi' },
    { state: uttarakhand, name: 'Almora' },
    { state: uttarakhand, name: 'Bageshwar' },
    { state: uttarakhand, name: 'Chamoli' },
    { state: uttarakhand, name: 'Champawat' },
    { state: uttarakhand, name: 'Dehradun' },
    { state: uttarakhand, name: 'Haridwar' },
    { state: uttarakhand, name: 'Nainital' },
    { state: uttarakhand, name: 'Pauri' },
    { state: uttarakhand, name: 'Pithoragarh' },
    { state: uttarakhand, name: 'Rudraprayag' },
    { state: uttarakhand, name: 'Tehri' },
    { state: uttarakhand, name: 'Udham Singh Nagar' },
    { state: uttarakhand, name: 'Uttarkashi' },
    { state: west_bengal, name: 'Alipurduar' },
    { state: west_bengal, name: 'Bankura' },
    { state: west_bengal, name: 'Birbhum' },
    { state: west_bengal, name: 'Cooch Behar' },
    { state: west_bengal, name: 'Dakshin Dinajpur' },
    { state: west_bengal, name: 'Darjeeling' },
    { state: west_bengal, name: 'Hooghly' },
    { state: west_bengal, name: 'Howrah' },
    { state: west_bengal, name: 'Jalpaiguri' },
    { state: west_bengal, name: 'Jhargram' },
    { state: west_bengal, name: 'Kalimpong' },
    { state: west_bengal, name: 'Kolkata' },
    { state: west_bengal, name: 'Malda' },
    { state: west_bengal, name: 'Murshidabad' },
    { state: west_bengal, name: 'Nadia' },
    { state: west_bengal, name: 'North 24 Parganas' },
    { state: west_bengal, name: 'Paschim Bardhaman' },
    { state: west_bengal, name: 'Paschim Medinipur' },
    { state: west_bengal, name: 'Purba Bardhaman' },
    { state: west_bengal, name: 'Purba Medinipur' },
    { state: west_bengal, name: 'Purulia' },
    { state: west_bengal, name: 'South 24 Parganas' },
    { state: west_bengal, name: 'Uttar Dinajpur' },
    { state: andaman_nicobar, name: 'Nicobar' },
    { state: andaman_nicobar, name: 'North Middle Andaman' },
    { state: andaman_nicobar, name: 'South Andaman' },
    { state: chandigarh, name: 'Chandigarh' },
    { state: dadra_nagar_haveli, name: 'Dadra Nagar Haveli' },
    { state: daman_diu, name: 'Daman' },
    { state: daman_diu, name: 'Diu' },
    { state: delhi, name: 'Central Delhi' },
    { state: delhi, name: 'East Delhi' },
    { state: delhi, name: 'New Delhi' },
    { state: delhi, name: 'North Delhi' },
    { state: delhi, name: 'North East Delhi' },
    { state: delhi, name: 'North West Delhi' },
    { state: delhi, name: 'Shahdara' },
    { state: delhi, name: 'South Delhi' },
    { state: delhi, name: 'South East Delhi' },
    { state: delhi, name: 'South West Delhi' },
    { state: delhi, name: 'West Delhi' },
    { state: lakshadweep, name: 'Lakshadweep' },
    { state: ladakh, name: 'Kargil' },
    { state: ladakh, name: 'Leh' },
    { state: puducherry, name: 'Karaikal' },
    { state: puducherry, name: 'Mahe' },
    { state: puducherry, name: 'Puducherry' },
    { state: puducherry, name: 'Yanam' }
  ]
)

teacher1 = Teacher.create(first_name: 'ganesh', middle_name: 'sitaram', last_name: 'kale', mother_name: 'indubai', gender: 'male', date_of_birth: '24/01/1993', date_of_join: '12/11/2015', aadhaar_card_number: '123654789852', education: 'M.com', speciality: 'hindi', contact: '9552273780', address: 'Saykhindi', is_active: true)
teacher2 = Teacher.create(first_name: 'achyut', middle_name: 'dilip', last_name: 'kadam', mother_name: 'lalita', gender: 'male', date_of_birth: '02/07/1996', date_of_join: '12/11/2018', aadhaar_card_number: '123654789777', education: 'M.C.A', speciality: 'I.T', contact: '7030462978', address: 'Saykhindi', is_active: true)
teacher3 = Teacher.create(first_name: 'suryakant', middle_name: 'dilip', last_name: 'kadam', mother_name: 'lalita', gender: 'male', date_of_birth: '16/05/1992', date_of_join: '12/11/2014', aadhaar_card_number: '123654789778', education: 'S.S.C', speciality: 'jistory', contact: '9673151455', address: 'Saykhindi', is_active: true)
teacher4 = Teacher.create(first_name: 'ravi', middle_name: 'dilip', last_name: 'kadam', mother_name: 'lalita', gender: 'male', date_of_birth: '31/03/1991', date_of_join: '10/11/2012', aadhaar_card_number: '123654789779', education: 'M.C.A', speciality: 'I.T', contact: '9158308762', address: 'Saykhindi', is_active: true)
teacher5 = Teacher.create(first_name: 'tejas', middle_name: 'chandrakant', last_name: 'kadam', mother_name: 'vanita', gender: 'male', date_of_birth: '06/09/2002', date_of_join: '10/11/2019', aadhaar_card_number: '123654788889', education: 'M.C.A', speciality: 'math', contact: '9158308752', address: 'Saykhindi', is_active: true)

standard1 = Standard.create(name: 'first')
classroom1_A = Classroom.create(division: 'A', medium: 'marathi', intake: 50, teacher_id: teacher1.id, standard_id: standard1.id)
classroom1_B = Classroom.create(division: 'B', medium: 'marathi', intake: 50, teacher_id: teacher2.id, standard_id: standard1.id)

standard2 = Standard.create(name: 'second')
classroom2_A = Classroom.create(division: 'A', medium: 'marathi', intake: 50, teacher_id: teacher3.id, standard_id: standard2.id)
classroom2_B = Classroom.create(division: 'B', medium: 'marathi', intake: 50, teacher_id: teacher4.id, standard_id: standard2.id)

standard3 = Standard.create(name: 'third')
classroom3_A = Classroom.create(division: 'A', medium: 'marathi', intake: 50, teacher_id: teacher5.id, standard_id: standard3.id)

student01 = Student.create(first_name: 'first_aa01', middle_name: 'middle_bb01', last_name: 'last_cc01', mother_name: 'mother_dd01', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325874', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_A.id)
student02 = Student.create(first_name: 'first_aa02', middle_name: 'middle_bb02', last_name: 'last_cc02', mother_name: 'mother_dd02', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325875', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_A.id)
student03 = Student.create(first_name: 'first_aa03', middle_name: 'middle_bb03', last_name: 'last_cc03', mother_name: 'mother_dd03', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325876', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_A.id)
student04 = Student.create(first_name: 'first_aa04', middle_name: 'middle_bb04', last_name: 'last_cc04', mother_name: 'mother_dd04', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325877', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_A.id)
student05 = Student.create(first_name: 'first_aa05', middle_name: 'middle_bb05', last_name: 'last_cc05', mother_name: 'mother_dd05', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325878', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_A.id)
student06 = Student.create(first_name: 'first_aa06', middle_name: 'middle_bb06', last_name: 'last_cc06', mother_name: 'mother_dd06', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325879', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_A.id)
student07 = Student.create(first_name: 'first_aa07', middle_name: 'middle_bb07', last_name: 'last_cc07', mother_name: 'mother_dd07', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325880', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_A.id)
student08 = Student.create(first_name: 'first_aa08', middle_name: 'middle_bb08', last_name: 'last_cc08', mother_name: 'mother_dd08', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325881', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_A.id)
student09 = Student.create(first_name: 'first_aa09', middle_name: 'middle_bb09', last_name: 'last_cc09', mother_name: 'mother_dd09', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325882', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_A.id)
student10 = Student.create(first_name: 'first_aa10', middle_name: 'middle_bb10', last_name: 'last_cc10', mother_name: 'mother_dd10', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325883', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_A.id)

student11 = Student.create(first_name: 'first_aa11', middle_name: 'middle_bb11', last_name: 'last_cc11', mother_name: 'mother_dd11', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325884', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_B.id)
student12 = Student.create(first_name: 'first_aa12', middle_name: 'middle_bb12', last_name: 'last_cc12', mother_name: 'mother_dd12', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325885', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_B.id)
student13 = Student.create(first_name: 'first_aa13', middle_name: 'middle_bb13', last_name: 'last_cc13', mother_name: 'mother_dd13', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325886', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_B.id)
student14 = Student.create(first_name: 'first_aa14', middle_name: 'middle_bb14', last_name: 'last_cc14', mother_name: 'mother_dd14', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325887', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_B.id)
student15 = Student.create(first_name: 'first_aa15', middle_name: 'middle_bb15', last_name: 'last_cc15', mother_name: 'mother_dd15', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325888', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_B.id)
student16 = Student.create(first_name: 'first_aa16', middle_name: 'middle_bb16', last_name: 'last_cc16', mother_name: 'mother_dd16', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325889', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_B.id)
student17 = Student.create(first_name: 'first_aa17', middle_name: 'middle_bb17', last_name: 'last_cc17', mother_name: 'mother_dd17', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325890', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_B.id)
student18 = Student.create(first_name: 'first_aa18', middle_name: 'middle_bb18', last_name: 'last_cc18', mother_name: 'mother_dd18', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325891', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_B.id)
student19 = Student.create(first_name: 'first_aa19', middle_name: 'middle_bb19', last_name: 'last_cc19', mother_name: 'mother_dd19', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325892', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_B.id)
student20 = Student.create(first_name: 'first_aa20', middle_name: 'middle_bb20', last_name: 'last_cc20', mother_name: 'mother_dd20', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325893', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard1.id, classroom_id: classroom1_B.id)

student21 = Student.create(first_name: 'first_aa21', middle_name: 'middle_bb21', last_name: 'last_cc21', mother_name: 'mother_dd21', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325894', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_A.id)
student22 = Student.create(first_name: 'first_aa22', middle_name: 'middle_bb22', last_name: 'last_cc22', mother_name: 'mother_dd22', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325895', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_A.id)
student23 = Student.create(first_name: 'first_aa23', middle_name: 'middle_bb23', last_name: 'last_cc23', mother_name: 'mother_dd23', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325896', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_A.id)
student24 = Student.create(first_name: 'first_aa24', middle_name: 'middle_bb24', last_name: 'last_cc24', mother_name: 'mother_dd24', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325897', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_A.id)
student25 = Student.create(first_name: 'first_aa25', middle_name: 'middle_bb25', last_name: 'last_cc25', mother_name: 'mother_dd25', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325898', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_A.id)
student26 = Student.create(first_name: 'first_aa26', middle_name: 'middle_bb26', last_name: 'last_cc26', mother_name: 'mother_dd26', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456325899', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_A.id)
student27 = Student.create(first_name: 'first_aa27', middle_name: 'middle_bb27', last_name: 'last_cc27', mother_name: 'mother_dd27', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258100', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_A.id)
student28 = Student.create(first_name: 'first_aa28', middle_name: 'middle_bb28', last_name: 'last_cc28', mother_name: 'mother_dd28', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258101', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_A.id)
student29 = Student.create(first_name: 'first_aa29', middle_name: 'middle_bb29', last_name: 'last_cc29', mother_name: 'mother_dd29', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258102', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_A.id)
student30 = Student.create(first_name: 'first_aa30', middle_name: 'middle_bb30', last_name: 'last_cc30', mother_name: 'mother_dd30', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258103', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_A.id)

student31 = Student.create(first_name: 'first_aa31', middle_name: 'middle_bb31', last_name: 'last_cc31', mother_name: 'mother_dd31', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258104', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_B.id)
student32 = Student.create(first_name: 'first_aa32', middle_name: 'middle_bb32', last_name: 'last_cc32', mother_name: 'mother_dd32', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258105', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_B.id)
student33 = Student.create(first_name: 'first_aa33', middle_name: 'middle_bb33', last_name: 'last_cc33', mother_name: 'mother_dd33', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258106', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_B.id)
student34 = Student.create(first_name: 'first_aa34', middle_name: 'middle_bb34', last_name: 'last_cc34', mother_name: 'mother_dd34', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258107', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_B.id)
student35 = Student.create(first_name: 'first_aa35', middle_name: 'middle_bb35', last_name: 'last_cc35', mother_name: 'mother_dd35', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258108', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_B.id)
student36 = Student.create(first_name: 'first_aa36', middle_name: 'middle_bb36', last_name: 'last_cc36', mother_name: 'mother_dd36', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258109', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_B.id)
student37 = Student.create(first_name: 'first_aa37', middle_name: 'middle_bb37', last_name: 'last_cc37', mother_name: 'mother_dd37', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258110', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_B.id)
student38 = Student.create(first_name: 'first_aa38', middle_name: 'middle_bb38', last_name: 'last_cc38', mother_name: 'mother_dd38', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258111', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_B.id)
student39 = Student.create(first_name: 'first_aa39', middle_name: 'middle_bb39', last_name: 'last_cc39', mother_name: 'mother_dd39', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258112', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_B.id)
student40 = Student.create(first_name: 'first_aa40', middle_name: 'middle_bb40', last_name: 'last_cc40', mother_name: 'mother_dd40', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258113', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard2.id, classroom_id: classroom2_B.id)

student41 = Student.create(first_name: 'first_aa41', middle_name: 'middle_bb41', last_name: 'last_cc41', mother_name: 'mother_dd41', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258114', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard3.id, classroom_id: classroom3_A.id)
student42 = Student.create(first_name: 'first_aa42', middle_name: 'middle_bb42', last_name: 'last_cc42', mother_name: 'mother_dd42', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258115', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard3.id, classroom_id: classroom3_A.id)
student43 = Student.create(first_name: 'first_aa43', middle_name: 'middle_bb43', last_name: 'last_cc43', mother_name: 'mother_dd43', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258116', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard3.id, classroom_id: classroom3_A.id)
student44 = Student.create(first_name: 'first_aa44', middle_name: 'middle_bb44', last_name: 'last_cc44', mother_name: 'mother_dd44', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258117', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard3.id, classroom_id: classroom3_A.id)
student45 = Student.create(first_name: 'first_aa45', middle_name: 'middle_bb45', last_name: 'last_cc45', mother_name: 'mother_dd45', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258118', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard3.id, classroom_id: classroom3_A.id)
student46 = Student.create(first_name: 'first_aa46', middle_name: 'middle_bb46', last_name: 'last_cc46', mother_name: 'mother_dd46', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258119', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard3.id, classroom_id: classroom3_A.id)
student47 = Student.create(first_name: 'first_aa47', middle_name: 'middle_bb47', last_name: 'last_cc47', mother_name: 'mother_dd47', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258120', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard3.id, classroom_id: classroom3_A.id)
student48 = Student.create(first_name: 'first_aa48', middle_name: 'middle_bb48', last_name: 'last_cc48', mother_name: 'mother_dd48', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258121', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard3.id, classroom_id: classroom3_A.id)
student49 = Student.create(first_name: 'first_aa49', middle_name: 'middle_bb49', last_name: 'last_cc49', mother_name: 'mother_dd49', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258122', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard3.id, classroom_id: classroom3_A.id)
student50 = Student.create(first_name: 'first_aa50', middle_name: 'middle_bb50', last_name: 'last_cc50', mother_name: 'mother_dd50', gender: 'male', date_of_birth: '14/02/1999', aadhaar_card_number: '987456258123', town: 'saykhindi', is_handicap: false, handicap_details: nil, is_active: true, standard_id: standard3.id, classroom_id: classroom3_A.id)

puts '========================='
puts 'Seed file successfully loaded!!!'
puts '========================='
